#*******************************************************************************
# IBM Confidential
# OCO Source Materials
# 5900-AM9
# (C) Copyright IBM Corp. 2020-2024 All Rights Reserved.
# The source code for this program is not  published or otherwise divested of
# its trade secrets, irrespective of what has been deposited with
# the U.S. Copyright Office.
#*******************************************************************************

resources:
  - manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: controller
    newName: controller
    newTag: latest
commonAnnotations:
  productChargedContainers: ""
  productID: 5d5997a033594f149a534a09802d60f1
  productMetric: VIRTUAL_PROCESSOR_CORE
  productName: IBM Support for Hyperledger Fabric
  productVersion: "1.0.0"
