#*******************************************************************************
# IBM Confidential
# OCO Source Materials
# 5900-AM9
# (C) Copyright IBM Corp. 2020-2024 All Rights Reserved.
# The source code for this program is not  published or otherwise divested of
# its trade secrets, irrespective of what has been deposited with
# the U.S. Copyright Office.
#*******************************************************************************

resources:
  - deployment.yaml

commonAnnotations:
  productName: "IBM Support for Hyperledger Fabric"
  productID: "5d5997a033594f149a534a09802d60f1"
  productVersion: "1.0.0"
  productChargedContainers: "peer"
  productMetric: "VIRTUAL_PROCESSOR_CORE"
