#!/bin/bash
#*******************************************************************************
# IBM Confidential
# OCO Source Materials
# 5900-AM9
# (C) Copyright IBM Corp. 2020-2024 All Rights Reserved.
# The source code for this program is not  published or otherwise divested of
# its trade secrets, irrespective of what has been deposited with
# the U.S. Copyright Office.
#*******************************************************************************

TESTTYPE=$TEST_TYPE

case "$TESTTYPE" in
    "checks")
        make $TEST_TYPE
        ;;
    "unit-tests")
        make $TEST_TYPE
        ;;
    "int-ginkgo-tests")
        make login image image-push
        make $TEST_TYPE
        ;;
esac
